//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameFeedback
    {
        public int FeedbackID { get; set; }
        public int UserID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
