//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameManagementMISEntities : DbContext
    {
        public GameManagementMISEntities()
            : base("name=GameManagementMISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackupLog> BackupLogs { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<GameFeedback> GameFeedbacks { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserLibrary> UserLibraries { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
