//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public int GameID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public decimal PriceAtPurchase { get; set; }
        public Nullable<decimal> DiscountApplied { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
